# Generated by Django 4.2.4 on 2023-08-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='turma',
            new_name='turno',
        ),
    ]
